language: python

archive: true


python:
  - "3.4"

before_install:
  - virtualenv -p $SHIPPABLE_PYTHON $HOME/ve/
  - source $HOME/ve/bin/activate

install:
  - pip install pytest


script:
  - py.test --verbose
